#!/usr/bin/env bash
# Generate the SERVER's .env (the USB's buendia.env) from the build-side deploy/.env.
#
#   ./make-site-env.sh                      # -> ./buendia.env, fresh DB passwords
#   ./make-site-env.sh --out /media/.../Buendia/buendia.env
#   ./make-site-env.sh --keep-passwords <existing buendia.env>
#
# Two .env files exist on purpose and must not be merged: deploy/.env drives the BUILD
# (build-apk.sh, publish.sh, pack-www.sh) and never leaves the build box; buendia.env is the
# SERVER's, installed by bootstrap.sh as /opt/buendia/.env. This script derives the second from
# the first so the addresses cannot drift — a mismatch between STATIC_IP here and the address
# baked into the APK produces tablets that install cleanly and never connect.
#
# --keep-passwords matters when a server already has its database: MySQL keeps the credentials
# from first boot, so regenerating them locks the stack out of its own data.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$HERE/../.env"
OUT="$PWD/buendia.env"; KEEP=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out) OUT="$2"; shift 2 ;;
    --keep-passwords) KEEP="$2"; shift 2 ;;
    -h|--help) sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[[ -f "$SRC" ]] || { echo "ERROR: $SRC not found" >&2; exit 1; }
set -a; . "$SRC"; set +a

# `tr </dev/urandom | head -c N` exits 141: head closes the pipe, tr takes SIGPIPE, pipefail
# propagates it and set -e aborts the script — silently, since nothing has been printed yet.
# The repo's gotcha list records this class of bug; the subshell with pipefail off contains it.
pw() { ( set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24 ); }
if [[ -n "$KEEP" ]]; then
  [[ -f "$KEEP" ]] || { echo "ERROR: $KEEP not found" >&2; exit 1; }
  ROOTPW="$(awk -F= '/^MYSQL_ROOT_PASSWORD=/{print $2; exit}' "$KEEP")"
  APPPW="$(awk -F= '/^MYSQL_PASSWORD=/{print $2; exit}' "$KEEP")"
  [[ -n "$ROOTPW" && -n "$APPPW" ]] || { echo "ERROR: no passwords found in $KEEP" >&2; exit 1; }
  echo "reusing the database passwords from $KEEP"
else
  ROOTPW="$(pw)"; APPPW="$(pw)"
fi

umask 077
cat > "$OUT" <<EOF
# Buendia field pilot — SERVER configuration for site '${SITE_ID}'.
# Generated by tools/make-site-env.sh from the build-side .env — do not hand-edit the
# addresses: STATIC_IP must stay equal to the address baked into the APK payload.
# bootstrap.sh installs this as /opt/buendia/.env (mode 0600). It is sourced by bash, so no
# spaces and none of  ; & | \$ \\ ' " * ? #  in a value unless it is single-quoted.

SITE_ID=${SITE_ID}
STATIC_IP=${STATIC_IP}
TZ=${TZ:-UTC}                            # keep UTC: the tablet renders device-local (A9)

# --- Networking: applied by 'setup.sh --finish', once cabled to OUR router ---
CONFIGURE_NETWORK=true
NET_IFACE=                        # the WIRED interface. Fill it in with:
                                  #   cd /opt/buendia && sudo ./tools/buendia-netcheck.sh --write
NET_PREFIX=24
NET_RENDERER=                     # empty = autodetect (NetworkManager on Ubuntu Desktop)
GATEWAY_IP=${ROUTER_IP:-192.168.8.1}
DNS_SERVERS=${ROUTER_IP:-192.168.8.1}     # our router's dnsmasq: the clock-intercept resolver
NET_ROUTE_METRIC=1000             # the wired route must LOSE to a Wi-Fi or tethered phone:
                                  #   that is how this laptop gets internet for remote support,
                                  #   and an unweighted wired route beats both and leads nowhere.

# WHICH ADDRESS the stack answers on. This is a data-protection control: when this laptop joins
# another Wi-Fi to get online, anything published on 0.0.0.0 is offered to that network too —
# and :9000 is patient data, :9001 serves the APK that carries the clinical password.
LAN_BIND=${STATIC_IP}

# --- Our Wi-Fi + facility name (printed on the in-zone install card) ---
SITE_WIFI_SSID='${SITE_WIFI_SSID}'
SITE_WIFI_PASSWORD='${SITE_WIFI_PASSWORD}'
SITE_FACILITY_NAME='${SITE_FACILITY_NAME}'

# --- The head router, configured FROM THIS SERVER by network/configure-router.sh ---
ROUTER_IP=${ROUTER_IP:-192.168.8.1}
ROUTER_COUNTRY=${ROUTER_COUNTRY:-CD}
ROUTER_CHANNEL_24=${ROUTER_CHANNEL_24:-6}
ROUTER_CHANNEL_5=${ROUTER_CHANNEL_5:-36}
ROUTER_HTMODE_24=${ROUTER_HTMODE_24:-HE20}
ROUTER_HTMODE_5=${ROUTER_HTMODE_5:-HE80}
ROUTER_TIMEZONE=${ROUTER_TIMEZONE:-UTC}
ROUTER_ENCRYPTION=${ROUTER_ENCRYPTION:-psk2}
# Router administration (SSH + web UI) answers only the cabled server. A tablet on the Wi-Fi
# is refused, which is the point: the passphrase is laminated on a ward wall.
ROUTER_ADMIN_LAN_ONLY=${ROUTER_ADMIN_LAN_ONLY:-true}
ROUTER_ADMIN_FROM=${ROUTER_ADMIN_FROM:-${STATIC_IP}}

# --- Images: pinned by DIGEST, pulled by 'setup.sh --prepare' while online ---
DB_IMAGE=${DB_IMAGE}
OPENMRS_IMAGE=${OPENMRS_IMAGE}
PKGSERVER_IMAGE=                  # empty = serve the www/ unpacked from the USB payload

# --- Database ---
MYSQL_ROOT_PASSWORD=${ROOTPW}
MYSQL_DATABASE=${MYSQL_DATABASE:-openmrs}
MYSQL_USER=${MYSQL_USER:-openmrs}
MYSQL_PASSWORD=${APPPW}

# --- The clinical login. The tablet app carries this password, so the two must agree:
# setup.sh rotates the server account to match it (with a fresh random salt, replacing the
# seed's committed one). Changing it later means a manual step on every tablet.
APK_OPENMRS_USER=${APK_OPENMRS_USER:-buendia}
APK_OPENMRS_PASSWORD=${APK_OPENMRS_PASSWORD:-buendia}

APK_SOURCE=auto                   # the payload is on the stick, so nothing is downloaded
DOCKER_VERSION=
ENABLE_REMOTE_SUPPORT=false
TAILSCALE_AUTHKEY=
EOF
chmod 600 "$OUT"
echo "wrote $OUT (0600)"
echo "  site=${SITE_ID}  server=${STATIC_IP}  router=${ROUTER_IP:-192.168.8.1}  ssid=${SITE_WIFI_SSID}"
echo "  NB the APK payload on the stick must bake in ${STATIC_IP} — pack-www.sh prints what it baked."
