#!/bin/bash
# Copyright 2019 The Project Buendia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Ensure that the correct version of the OpenMRS platform WAR has been
# downloaded and configured.

SERVER_ID=server
SERVER_DIR=$HOME/openmrs/$SERVER_ID
PLATFORM_VERSION=1.10.6
WAR_URL=http://sourceforge.net/projects/openmrs/files/releases/OpenMRS_Platform_${PLATFORM_VERSION}/openmrs.war/download
WAR_MD5=31f9d67cb3debf45ab9486a069968289

# Pin the OpenMRS SDK Maven plugin to the last 3.x release (Apr 2021). 3.x
# is compiled to Java 7 bytecode; 4.x+ requires Java 8. We need Java 7 because
# OpenMRS 1.10.x ships Spring 3.0.5, whose JdkVersion class doesn't recognise
# Java 8+ and trips the validateJavaVersion check at server startup.
SDK_PLUGIN=org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:3.13.9

# go to the root of the Buendia repository
cd $(dirname $0)/..

# Install the OpenMRS SDK configuration properties if needed.
if [ ! -d $SERVER_DIR ]; then
    echo "Configuring OpenMRS SDK..."
    mkdir -p $SERVER_DIR
    # Install the properties files so that the setup-sdk task doesn't ask
    cp -a openmrs/properties/*.properties $SERVER_DIR/..
    # Then run setup-sdk so that the Maven cache gets populated
    mvn $SDK_PLUGIN:setup-sdk -DserverId=$SERVER_ID
fi

# Install the OpenMRS WAR if needed.
OPENMRS_WAR_FILE=$SERVER_DIR/openmrs-$PLATFORM_VERSION.war
if [ ! -f $OPENMRS_WAR_FILE ]; then
    echo "Fetching OpenMRS platform WAR..."
    tools/fetch $WAR_URL $WAR_MD5 $OPENMRS_WAR_FILE
    echo "Installing default OpenMRS properties..."
    cp -a openmrs/properties/$SERVER_ID/* $SERVER_DIR
fi

echo "OpenMRS SDK ready."
